apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-agency-data
  namespace: the-agency
  labels:
    app: the-agency
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
